export const doctors = [
  {
    name: "Dr. Rajender Kumar",
    slug: "dr-rajender-kumar",
    avatar: "https://res.cloudinary.com/dhtxrpqna/image/upload/1000096945-removebg-preview_pqnqvq.png",
    about:
      "Renowned Radiation Oncologist with over 25 years of experience treating prostate, breast, lung, and brain cancers. Known for pioneering advanced therapies across North Delhi.",
    specialization: "Radiation Oncology",
    experience: "25+ years",
    tags: [
      "Orthopedics",
      "Join Replacement",
    ],
  },
  {
    name: "Dr Jitesh Manghwani",
    slug: "dr-jitesh-manghwani",
    avatar: "https://res.cloudinary.com/dhtxrpqna/image/upload/1000096908-removebg-preview_ekqngw.png",
    about:
      "Orthopaedic Spine Surgeon at Max Hospital, Shalimar Bagh. Featured on Health 360 with Sneha Mordani.",
    specialization: "Orthopaedic Spine Surgery",
    experience: "10 years",
    tags: [
      "Spine Surgery Expert",
      "Orthopaedic Care",
      "Robotic surgery",
    ],
  },
  {
    name: "Dr. Arjun Patel",
    slug: "dr-arjun-patel",
    avatar: "/doctor2.png",
    about: "Orthopedic surgeon specializing in minimally invasive techniques",
    specialization: "Orthopedics",
    experience: "12 years",
    tags: [
      "Minimally Invasive",
      "Sports Injury Expert",
      "Arthroscopy Specialist",
      "Bone Health",
      "FractureCare",
      "Joint Pain Relief",
      "Spine Specialist",
      "Orthopedic Surgeon",
    ],
  },
  {
    name: "dr-clara-whitmore",
    avatar: "/doctor3.png",
    about: "Neurologist researching advanced treatments for Parkinson's",
    specialization: "Neurology",
    experience: "8 years",
    tags: [
      "Parkinsons Expert",
      "BrainHealth",
      "Neurology Care",
      "Migraine Specialist",
      "Stroke Prevention",
      "EpilepsyCare",
      "Neuro Research",
      "Memory Disorders",
      "Nerve Health",
    ],
  },
  {
    name: "dr-sanjay-mehta",
    avatar: "/doctor4.png",
    about: "Oncologist with expertise in precision cancer therapies",
    specialization: "Oncology",
    experience: "14 years",
    tags: [
      "CancerCare",
      "Precision Oncology",
      "Chemotherapy Expert",
      "Tumor Specialist",
      "Cancer Research",
      "Immunotherapy",
      "Radiation Therapy",
      "HopeFor Cancer",
      "Survivor Care",
    ],
  },
];